### PR TITLE
SQOOP-3430: Remove the old maven pom

### PR DESCRIPTION
**Pull request by Fokko**
Both Ant and Gradle are enough

### CODE REVIEW

**Comment by Fokko** [comment]
The file will still be available in GIT if we really need it after 7 years.

**Comment by Fokko** [comment]
Rebased to make the CI happy :)

**Comment by szvasas** [comment]
I am pretty sure we don't need this file anymore, but if we do we can easily restore it so merging this to trunk.
Thank you for your contribution @Fokko!

**Comment by Fokko** [comment]
Thanks @szvasas

**Pull request merged**
