### PR TITLE
SQOOP-3427 Add Travis badge to the README

### PR DESCRIPTION
**Pull request by Fokko**
We all love badges: https://jira.apache.org/jira/browse/SQOOP-3427

### CODE REVIEW

**Review by fszabo2 — COMMENTED** [review]
Hi @Fokko,

Thanks for submitting this patch!
Could you remove the old README.txt file as well so we don't duplicate information?
(Or do you think we should keep it?)

In any case, badges are awesome!

**Comment by Fokko** [comment]
Thanks for looking into this @fszabo2 

I've removed the old README. I think we should get rid of it since it is almost the same as the new one.

**Comment by Fokko** [comment]
I also took the liberty to include Koen's work in https://github.com/apache/sqoop/pull/31 into this PR.

**Comment by fszabo2** [comment]
Hi @Fokko,

Sorry for my late responses, I have quite limited bandwidth these days for Sqoop.

Anyway, could you please rebase this on the current trunk, so we can see if your fix for the CI took effect?

**Comment by Fokko** [comment]
Thanks for taking the time. I've rebased the PR.

Probably I'll do a couple of more PR's in the upcoming days to fix the compiler warnings, make better use of try-with-resources and bumping some of the dependencies to fix security issues.

**Comment by szvasas** [comment]
Hi @Fokko,

I have submitted a PR for your branch with my suggestions: https://github.com/Fokko/sqoop/pull/1/files
I basically renamed COMPILING.txt to COMPILING.adoc so GitHub will format it by default and I refer it from README.md.

**Comment by Fokko** [comment]
Thanks @szvasas 

Sorry for taking so long, I was a bit busy lately.

**Pull request merged**
