### PR TITLE
Fix the CI by updating the db2 test

### PR DESCRIPTION
**Pull request by Fokko**
Replaces db2express with the db2 instance by IBM: https://hub.docker.com/r/ibmcom/db2/

Removed the init script since we can now use the `DBNAME` environment variable. Also updated the driver with the appropriate version.

### CODE REVIEW

**Comment by Fokko** [comment]
PTAL @fszabo2 @ebogi 

Would be great to get master green again :-)

**Review by fszabo2 — APPROVED** [review]
LGTM, it's good to see a green Travis! 

Let's wait a day and see if somebody wants to add a comment here!

**Comment by ebogi** [comment]
LGTM too. Thanks @Fokko for fixing the CI!

**Comment by fszabo2** [comment]
Hi @Fokko ,

I've merged your pull request! Thank you for this contribution!

**Comment by Fokko** [comment]
My pleasure @fszabo2, thank you for merging.

**Pull request merged**
