### PR TITLE
SQOOP-3428 Fix the CI

### PR DESCRIPTION
**Pull request by Fokko**
https://jira.apache.org/jira/browse/SQOOP-3430

PTAL @fszabo2 @szvasas

### CODE REVIEW

**Comment by fszabo2** [comment]
Hi,

I haven't had a lot of time to look into it, but looks like the init scripts are not getting invoked:
src/scripts/thirdpartytest/docker-compose/oraclescripts/startup/oracleusersetup.sql

or the script itself just fails?

I've found this in my docker logs:

```
Starting Oracle Net Listener.
Starting Oracle Database 11g Express Edition instance.
ERROR:
ORA-28002: the password will expire within 7 days
User created.
User altered.
Grant succeeded.
```

**Comment by Fokko** [comment]
Thanks @fszabo2 for looking into it. I will pick this up today, and see if we can get it to work again.

The old Docker image has been removed due to the Docker DMCA Takedown Notice from the Copyright owner which is the Oracle.

**Comment by Fokko** [comment]
@fszabo2 All nice and green again :-)

**Review by fszabo2 — APPROVED** [review]
LGTM, ship it! :)

**Pull request merged**
