### PR TITLE
SQOOP-3462 Sqoop ant build fails due to outdated maven repo URLs

### PR DESCRIPTION
**Pull request by stoty**
use https://repo1.maven.org URL int ant build.

### CODE REVIEW

**Comment by iwasakims** [comment]
+1(non-binding). I got the same issue while building Bigtop packages ([BIGTOP-3291](https://issues.apache.org/jira/browse/BIGTOP-3291)) and the patch here resolved the issue. CI test failure looks unrelated.

**Comment by szvasas** [comment]
+1, checked it on my machine as well and it solves the issue.
I have closed and reopened the PR to re-trigger the CI build but the failure was indeed not related.

Btw, does anyone still uses the Ant build? I remember we wanted to remove it and keep the Gradle build only.

**Review by szvasas — APPROVED** [review]

**Comment by stoty** [comment]
ATM both Cloudera HDP and CDPD uses the ant build, and I think CDH does 
as well.

**Comment by szvasas** [comment]
Oh yes, those distributions still use it, but I meant other upstream projects/infrastructures.
@iwasakims, I see you were also interested in this patch, I guess that means that Bigtop uses the Ant build in Sqoop.
If we removed the Ant build and switch to Gradle completely would that generate a considerable amount of work in Bigtop?

**Comment by iwasakims** [comment]
> If we removed the Ant build and switch to Gradle completely would that generate a considerable amount of work in Bigtop?

I think moving to gradle itself is easy. Just fixing [a line in packaging script](https://github.com/apache/bigtop/blob/master/bigtop-packages/src/common/sqoop/do-component-build#L24). We can do it when Bigtop bump Sqoop to the release having [SQOOP-3052](https://issues.apache.org/jira/browse/SQOOP-3052) (from current 1.4.6).

**Comment by iwasakims** [comment]
I filed [BIGTOP-3294](https://issues.apache.org/jira/browse/BIGTOP-3294) for this.

**Comment by szvasas** [comment]
Sounds great, thank you @iwasakims!

**Pull request merged**
